---
title: "CS 7580 -- Intensive Software, Construction and Engineering (ISCE)"
navlink: "[jv](http://janvitek.org/)"
footer:
  - content: '[PRL](http://prl.ccs.neu.edu/) • [CCIS](http://ccis.neu.edu/)<br/>'
  - content: 'Copyright Northeastern University, 2019'
output: markdowntemplates::skeleton
---

 --------------   --------------------------------------
  **Schedule**    Wed, 6--9:15pm @ Richards 237
     **Staff**    [Jan Vitek](http://janvitek.org) 
   **Contact**    [Piazza](https://piazza.com/class/jxj2gpglhna5ob) for all communication.
   ------------   --------------------------------------

#### Syllabus

Much of today's software engineering aims to automate the process of understanding software artifacts. 
This graduate class focuses on analysis of computer programs for purposes such as finding 
security vulnerabilities and errors, or understanding the software development process.
My goal is to give you a working knowledge of program analysis and its theoretical foundations rooted 
in abstract interpretation.
The class is split in two. We start with lectures on key concepts of program analysis 
including: data flow analysis and abstract interpretation; applications to security, bug finding and testing; 
dynamic analysis; and machine-learning based approaches that tradeoff soundness in favor of scalability.
The second part, focuses on reading, presenting and validating research papers. 

#### Workload and Grading

My expectation is that most of you will spend about a day a week on the course. 
Most of the work is reading and writing. 
There opportunities for programming are in the second half, but are optional. 
The deliverables are:

 * Assignments: questions on  course material. (3x)
 * Midterm: same as assignments, in-class, on October 23.  (1x)
 * Reviews: a one page review of a research paper. (2x)
 * Presentation: a lecture on your chosen research paper. Done in group. (1x)
 * Project: a blog post describing the outcome of your reproduction and a presentation. Done in group. (1x)

The project is the only only open-ended task. 

Grades are somewhat besides the point in a research class, but they are required.
My expectation for the range of final grades is [B, B+, A-, A], where the semantics 
of the letter grades are that B is a below average, B+ and A- means you met expectations and A+ means you exceeded them.

#### Project

Working in groups of up to 3 students, you will select a research paper, obtain its data and code from the authors, and perform a reproduction study.
You will present the paper in class, and then report on your reproduction.

###### Reproduction study

There are three alternatives:  _repetition_, _reanalysis_, or _reproduction_.  Detail descriptions of those terms are in this [paper](https://arxiv.org/abs/1901.10220). 
A repetition attempts to establish that given the code and data provided by the authors, the results of the paper hold. 
Reanalysis starts from the author's code and data, but attempts to evaluate if the results are robust in the presence of changes to the methodology.  Reproduction attempt to reimplement some part of the approach and determine if the same conclusions can still be obtained.  

###### Report

Your report should do the following: (1) summarize the paper's approach and results, (2) describe how you validated the results, and (3) summarize what you found. In simple cases, when all is as claimed, the report can be  just a couple of pages. If there are interesting differences a  report could be extended into a full paper.

###### Lecture

Each group will prepare a lecture on their paper. The lecture is 90 minutes long including time for questions and discusion. The goal is to give an in-depth presentation of the paper, placing it in context of previous research and talk about is strenghs and limitation.

#### Assignments

We will have 3 in-class assignments, each one will consist of about 3 questions from  the textbook.

 
#### Papers

Here are some ideas for papers to reproduce.
We are looking for papers that come with software and data. 
You can choose other papers, e.g. from recent proceedings of conferences such as ICSE, FSE, ASE and OOPSLA.

###### Testing

 * [Fairness Testing: Testing Software for Discrimination](https://dl.acm.org/citation.cfm?id=3106277) FSE'17
 * [Do Automatically Generated Unit Tests Find Real Faults?](https://dl.acm.org/citation.cfm?id=2916135.2916250) ASE'15
 * [QuickChecking Static Analysis Properties](https://doi.org/10.1002/stvr.1640) STVR'17 

###### Bug finding

 * [Finding Broken Promises in Asynchronous JavaScript Programs](https://doi.org/10.1145/3276532) OOPSLA'18 
 * [ExceLint: Automatically Finding Spreadsheet Formula Errors](https://doi.org/10.1145/3276518) OOPSLA'18
 * [To Type or Not to Type: Quantifying Detectable Bugs in JavaScript](https://dl.acm.org/citation.cfm?id=3097459) ICSE'17 

###### Security 

 * [Automated Identification of Security Issues from Commit Messages and Bug Reports](https://dl.acm.org/citation.cfm?id=3117771) FSE'17 
 * [ZENIDS: Introspective Intrusion Detection for PHP Applications](https://dl.acm.org/citation.cfm?id=3097397) ICSE'17

###### Algorithms  

 * [Active Learning of Points-To Specifications](http://doi.org/10.1145/3192366.3192383)  PLDI'18
 * [P/Taint: Unified Points-to and Taint Analysis](https://doi.org/10.1145/3133926) OOPSLA'17
 * [Modular static analysis of string manipulations in C programs](https://hal.sorbonne-universite.fr/hal-01884772/document) SAS'18

###### Big Code

 * [Automatically Diagnosing and Repairing Error Handling Bugs in C](https://dl.acm.org/citation.cfm?id=3106300) FSE'17
 * [Recovering Clear, Natural Identifiers from Obfuscated JS Names](https://dl.acm.org/citation.cfm?id=3106289) FSE'17  

#### Lectures

Lectures are in the evening (3 hours and 15 minutes each Wednesday).

 + **Sep. 04:** Course overview.  _Due:_ Read PPA Ch.1, Submit pitches.
 + **Sep. 11:** Dataflow analysis. _Due:_  Read PPA Ch.2. Return assignment 1.
 + **Sep. 18:** Constraint-based analysis. _Due:_ Read PPA Ch.3. Return assignment 2.
 + **Sep. 25:** Abstract interpretation. _Due:_ Read PPA Ch.4. Return assignment 3.
 + **Oct. 02:** Abstract interpretation.
 + **Oct. 09:** Dynamic analysis, BigCode and machine learning.
 + **Oct. 16:** Guest lectures: applications to security and bug finding.
 + **Oct. 23:** Midterm (PPA Ch 1-4)
 + **Oct. 30:** _Due:_ Project updates, previews of next week's talks.
 + **Nov. 06:** _Due:_ Two talks, reviews, previews of next week's talks
 + **Nov. 13:** _Due:_ Two talks, reviews, previews of next week's talks
 + **Nov. 20:** _Due:_ Two talks, reviews, previews of next week's talks
 + **Dec. 04:** _Due:_ Two talks, reviews.
 + **Dec. 11:** _Due:_ Final project presentations

#### Textbook

The textbook is [Principle of Program Analysis](https://www.amazon.com/Principles-Program-Analysis-Flemming-Nielson-dp-3642084745/dp/3642084745/ref=mt_paperback?_encoding=UTF8&me=&qid=) (PPA) by F. Nielson, H.R. Nielson and C. Hankin.  (An old version of the text is on ResearchGate [here](https://www.researchgate.net/publication/265352570_Principles_of_Program_Analysis). The newest edition has 476 pages.)


####  Reviews from past classes

_"Jan Vitek is the most horrible professor I've ever met. [...] he made students read and learn all by themselves. [...] He kind of enjoys watching students working so hard  over night and night"_

You are warned.
